name: Run tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7.2'

      - name: Install gems
        run: bundle install

      - name: Setup Chrome driver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '110.0.5481.77'

      - name: Start Chrome driver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run tests
        run: ENVIRONMENT=ci bundle exec rspec specs
